---
# installing gradle

- name: Gradle | Download gradle
  get_url:
    url: "https://services.gradle.org/distributions/gradle-{{gradle_version}}-all.zip"
    dest: "/tmp/gradle-{{gradle_version}}-all.zip"

- name: Gradle | apt-get update
  apt: update_cache=yes
  
- name: Gradle | Install unzip
  apt: pkg=unzip state=latest

- name: Gradle | Unpack the compressed Gradle
  command: unzip /tmp/gradle-{{gradle_version}}-all.zip -d /usr/local

- name: Grade | Rename Gradle folder
  command: mv /usr/local/gradle-{{gradle_version}} /usr/local/gradle

- name: Gradle | Set the permissions on the Gradle binary
  file:
    path: "/usr/local/gradle/bin"
    state: directory
    mode: 0755
    recurse: yes

- stat: path=/etc/profile.d/gradle.sh
  register: p

- name: Gradle | create Gradle profile.d config
  file: path=/etc/profile.d/gradle.sh state=touch owner=root group=sys mode=0755
  when: p.stat.exists is defined and not p.stat.exists

- name: Gradle | export gradle home stuff
  blockinfile:
    dest: /etc/profile.d/gradle.sh
    block: |
      export GRADLE_HOME=/usr/local/gradle
      export PATH=${GRADLE_HOME}/bin:${PATH}

- name: Gradle | Refresh the PATH
  shell: . /etc/profile
